    v1 = staging_folder + "/" + eye + vr_sides[0] + '_' + base_video_name + '.avi'
    fr1 = openshot.FFmpegReader(v1)
    c1 = openshot.Clip(fr1)
    c1.Layer(1)
    print('Clip created')
    print('Adding clip')
    t.AddClip(c1)
    print('Clip added')
    mp1 = resolve_vr_mask_path(resolution[1], vr_sides[0], vr_format)
    mr1 = openshot.QtImageReader(mp1)
    br1 = openshot.Keyframe()
    br1.AddPoint(1, 0.0, openshot.LINEAR)
    co1 = openshot.Keyframe()
    co1.AddPoint(1, 0.0, openshot.LINEAR)
    m1 = openshot.Mask(mr1, br1, co1)
    m1.Layer(1)
    m1.End(fr1.info.duration)
    print('Mask created')
    t.AddEffect(m1)

    v2 = staging_folder + "/" + eye + vr_sides[1] + '_' + base_video_name + '.avi'
    fr2 = openshot.FFmpegReader(v2)
    c2 = openshot.Clip(fr2)
    c2.Layer(2)
    print('Clip created')
    print('Adding clip')
    t.AddClip(c2)
    print('Clip added')
    mp2 = resolve_vr_mask_path(resolution[1], vr_sides[1], vr_format)
    mr2 = openshot.QtImageReader(mp2)
    br2 = openshot.Keyframe()
    br2.AddPoint(1, 0.0, openshot.LINEAR)
    co2 = openshot.Keyframe()
    co2.AddPoint(1, 0.0, openshot.LINEAR)
    m2 = openshot.Mask(mr2, br2, co2)
    m2.Layer(2)
    m2.End(fr2.info.duration)
    print('Mask created')
    t.AddEffect(m2)

    v3 = staging_folder + "/" + eye + vr_sides[2] + '_' + base_video_name + '.avi'
    fr3 = openshot.FFmpegReader(v3)
    c3 = openshot.Clip(fr3)
    c3.Layer(3)
    print('Clip created')
    print('Adding clip')
    t.AddClip(c3)
    print('Clip added')
    mp3 = resolve_vr_mask_path(resolution[1], vr_sides[2], vr_format)
    mr3 = openshot.QtImageReader(mp3)
    br3 = openshot.Keyframe()
    br3.AddPoint(1, 0.0, openshot.LINEAR)
    co3 = openshot.Keyframe()
    co3.AddPoint(1, 0.0, openshot.LINEAR)
    m3 = openshot.Mask(mr3, br3, co3)
    m3.Layer(3)
    m3.End(fr3.info.duration)
    print('Mask created')
    t.AddEffect(m3)

    v4 = staging_folder + "/" + eye + vr_sides[3] + '_' + base_video_name + '.avi'
    fr4 = openshot.FFmpegReader(v4)
    c4 = openshot.Clip(fr4)
    c4.Layer(4)
    print('Clip created')
    print('Adding clip')
    t.AddClip(c4)
    print('Clip added')
    mp4 = resolve_vr_mask_path(resolution[1], vr_sides[3], vr_format)
    mr4 = openshot.QtImageReader(mp4)
    br4 = openshot.Keyframe()
    br4.AddPoint(1, 0.0, openshot.LINEAR)
    co4 = openshot.Keyframe()
    co4.AddPoint(1, 0.0, openshot.LINEAR)
    m4 = openshot.Mask(mr4, br4, co4)
    m4.Layer(4)
    m4.End(fr4.info.duration)
    print('Mask created')
    t.AddEffect(m4)

    if sides_per_eye >= 5:
        v5 = staging_folder + "/" + eye + vr_sides[4] + '_' + base_video_name + '.avi'
        fr5 = openshot.FFmpegReader(v5)
        c5 = openshot.Clip(fr5)
        c5.Layer(5)
        print('Clip created')
        print('Adding clip')
        t.AddClip(c5)
        print('Clip added')
        mp5 = resolve_vr_mask_path(resolution[1], vr_sides[4], vr_format)
        mr5 = openshot.QtImageReader(mp5)
        br5 = openshot.Keyframe()
        br5.AddPoint(1, 0.0, openshot.LINEAR)
        co5 = openshot.Keyframe()
        co5.AddPoint(1, 0.0, openshot.LINEAR)
        m5 = openshot.Mask(mr5, br5, co5)
        m5.Layer(5)
        m5.End(fr5.info.duration)
        print('Mask created')
        t.AddEffect(m5)

    if sides_per_eye >= 6:
        v6 = staging_folder + "/" + eye + vr_sides[5] + '_' + base_video_name + '.avi'
        fr6 = openshot.FFmpegReader(v6)
        c6 = openshot.Clip(fr6)
        c6.Layer(6)
        print('Clip created')
        print('Adding clip')
        t.AddClip(c6)
        print('Clip added')
        mp6 = resolve_vr_mask_path(resolution[1], vr_sides[5], vr_format)
        mr6 = openshot.QtImageReader(mp6)
        br6 = openshot.Keyframe()
        br6.AddPoint(1, 0.0, openshot.LINEAR)
        co6 = openshot.Keyframe()
        co6.AddPoint(1, 0.0, openshot.LINEAR)
        m6 = openshot.Mask(mr6, br6, co6)
        m6.Layer(6)
        m6.End(fr6.info.duration)
        print('Mask created')
        t.AddEffect(m6)

    if sides_per_eye >= 7:
        v7 = staging_folder + "/" + eye + vr_sides[6] + '_' + base_video_name + '.avi'
        fr7 = openshot.FFmpegReader(v7)
        c7 = openshot.Clip(fr7)
        c7.Layer(7)
        print('Clip created')
        print('Adding clip')
        t.AddClip(c7)
        print('Clip added')
        mp7 = resolve_vr_mask_path(resolution[1], vr_sides[6], vr_format)
        mr7 = openshot.QtImageReader(mp7)
        br7 = openshot.Keyframe()
        br7.AddPoint(1, 0.0, openshot.LINEAR)
        co7 = openshot.Keyframe()
        co7.AddPoint(1, 0.0, openshot.LINEAR)
        m7 = openshot.Mask(mr7, br7, co7)
        m7.Layer(7)
        m7.End(fr7.info.duration)
        print('Mask created')
        t.AddEffect(m7)

    if sides_per_eye >= 8:
        v8 = staging_folder + "/" + eye + vr_sides[7] + '_' + base_video_name + '.avi'
        fr8 = openshot.FFmpegReader(v8)
        c8 = openshot.Clip(fr8)
        c8.Layer(8)
        print('Clip created')
        print('Adding clip')
        t.AddClip(c8)
        print('Clip added')
        mp8 = resolve_vr_mask_path(resolution[1], vr_sides[7], vr_format)
        mr8 = openshot.QtImageReader(mp8)
        br8 = openshot.Keyframe()
        br8.AddPoint(1, 0.0, openshot.LINEAR)
        co8 = openshot.Keyframe()
        co8.AddPoint(1, 0.0, openshot.LINEAR)
        m8 = openshot.Mask(mr8, br8, co8)
        m8.Layer(8)
        m8.End(fr8.info.duration)
        print('Mask created')
        t.AddEffect(m8)

